language: java
cache:
  directories:
    - $HOME/.gradle
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
script:
  - chmod +x gradlew
  - ./gradlew sonarqube -Dsonar.projectKey=saifali40_mapper -Dsonar.organization=saifali40-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
